---
title: "ACS data anaysis"
output:
  github_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F,message=F,warning=F)
```

```{r load data,cache=T }
d<-read.delim("../acs_clinical_DB.txt", header = T, sep = ",", dec = ".")

#manipulate to match variable names and coding with Rishi's data dictionary

d[d=="999"|d=="998"]<-NA
d[d==""]<-NA
library(tidyr)
library(dplyr)
d<-as_tibble(d)
d<-filter(d,!is.na(SubjectID))
#correct error in QFT result
d$QFT_TBAg_Nil[d$QFT_TBAg_Nil=="positive"]<-12.6
d$QuantiferonInTubeResult[d$QuantiferonInTubeResult=="12.6"]<-"positive"
d$QFT_TBAg_Nil<-as.numeric(d$QFT_TBAg_Nil)
d<-rename(d,studyid=SubjectID,
          age=AgeAtLastBirthDay,
          contact=LivedInHouseWithTBPatient,
          prevbcg=VaccinatedWithBCG,
          prevtbdiag=PreviousDiagnosisOfTB,
          prevtbdiagyear=YearPreviousDiagnosisTB,
          ethinicity=Ethnicity,
          hivpos=HIVPositive,
          height=Height,
          weight=Weight,
          recruitmentdate=EnrolmentDate,
          censordate=DateCensor,
          studytime=DateSurvExit,
          dateofdeath=DateDeath,
          ltfu_date=DateAWOL,
          mantoux_date=DateTSTRead,
          mantoux_result=TSTResult,
          qfngit_date=DateOfQuantiferon,
          igrapos=QuantiferonInTubeResult,
          qfngit_tbag_nil=QFT_TBAg_Nil,
          sex=Sex)
d$mantoux_result<-as.numeric(d$mantoux_result)
#study ID 40371 has invalid TST result. No numeric value"
d[,c("studytime","dateofdeath","ltfu_date","censordate","recruitmentdate","qfngit_date","mantoux_date")]<-lapply(d[,c("studytime","dateofdeath","ltfu_date","censordate","recruitmentdate","qfngit_date","mantoux_date")],as.Date.character)
d$igrapos<-as.factor(d$igrapos)
d$igrapos<-factor(d$igrapos,levels=c("positive","negative"),labels = c("positive","negative"))          

d<-mutate(d,diabetes=ifelse(ChronicIllnessDetails=="diabetes",1,0),
          bmi=weight/(height^2),
          died=ifelse(!is.na(dateofdeath),1,0),
          ltfu=ifelse(!is.na(ltfu_date),1,0),
          activetb=ifelse(TBCaseType=="prevalent"|is.na(TBCaseType),0,1),
          activetbdate=ifelse(activetb==1,studytime,NA),
          mantoux_bin=ifelse(mantoux_result>=5,1,0),
          qfngit_result=igrapos)
d$sex<-as.factor(d$sex)
d$sex<-factor(d$sex,levels=c("male","female"))
d$contact<-as.factor(d$contact)
d$BCGScar<-as.factor(d$BCGScar)
d$prevtbdiag<-as.factor(d$prevtbdiag)
d$hivpos<-as.factor(d$hivpos)
d$igrapos<-as.factor(d$igrapos)
d$igrapos<-factor(d$igrapos,levels=c("negative","positive"))
d$mantoux_bin<-as.factor(d$mantoux_bin)
d$mantoux_bin<-factor(d$mantoux_bin,levels=c("0","1"),labels=c("negative","positive"))
d$activetb<-as.factor(d$activetb)
d$activetb<-factor(d$activetb, levels=c(0,1),labels=c("no","yes"))


#estimate TB incidence. Include only baseline visit
d2<-filter(d,VisitType=="D0")
#exclude participants with prevalent TB and one HIV+ participant
d2<-filter(d2,TBCaseType=="incident"|is.na(TBCaseType))
d2<-filter(d2,hivpos!=1)
d2<-mutate(d2,followup=as.numeric(studytime-recruitmentdate))

#exclude participants without followup
d2<-filter(d2,followup>0)

```

Characteristics of participants 

```{r table1}
library(table1)
table1(~activetb+mantoux_bin+mantoux_result+igrapos+qfngit_tbag_nil+contact+age+sex+prevtbdiag+prevbcg+bmi+MotherGrossMonthlyIncome +FatherGrossMonthlyIncome+GuardianGrossMonthlyIncome+followup,data=d2)

```


# Missing data

```{r missing data}
library(VIM)
library(FactoMineR)
library(missMDA)
library(naniar)
library(dplyr)
d4<-select(d2,activetb,mantoux_bin,igrapos,contact,age,sex,prevtbdiag,prevbcg,bmi,MotherGrossMonthlyIncome,followup)
gg_miss_var(d4)
res<-summary(aggr(d4, sortVar=TRUE))$combinations
```

```{r incidence,results="hide"}
library(dplyr)
d2$activetb<-as.numeric(d2$activetb)
d2$activetb<-d2$activetb-1
inc<-d2 %>% select(followup,mantoux_bin,activetb,igrapos) %>% group_by(mantoux_bin,igrapos) %>% summarise_at(c("activetb","followup"),sum,na.rm=T)
inc_tst<-inc %>% group_by(mantoux_bin) %>% summarise_at(c("activetb","followup"),sum, na.rm=T)
inc_tst<-mutate(inc_tst,ir=activetb/(followup/365)*100)
inc_qft<-inc %>% group_by(igrapos) %>% summarise_at(c("activetb","followup"),sum, na.rm=T)
inc_qft<-mutate(inc_qft,ir=activetb/(followup/365)*100)
```
Overall incidence rate `r round(sum(d2$activetb==1)/(sum(d2$followup)/365)*100,2)` per 100p-y

```{r incidence1}
inc_tst
inc_qft
```


# Survival analysis
```{r cox}
library(gtsummary)
library("survival")
#binary cox

library("survminer")
fit<-coxph(Surv(followup, activetb) ~ mantoux_bin, data = d2)
tbl_regression(fit,exponentiate = T)

fit<-coxph(Surv(followup, activetb) ~ igrapos, data = d2)
tbl_regression(fit,exponentiate = T)

#explore different TST cut-off values

d2<-mutate(d2,tst10=ifelse(mantoux_result>=10,1,0),
           tst15=ifelse(mantoux_result>=15,1,0),
           tst_stratify=ifelse(mantoux_result>=15&prevbcg=="yes",1,
                               ifelse(mantoux_result>=5&prevbcg=="no",1,0)
                               )
           )
fit<-coxph(Surv(followup, activetb) ~ tst10, data = d2)
tbl_regression(fit,exponentiate = T)
fit<-coxph(Surv(followup, activetb) ~ tst15, data = d2)
tbl_regression(fit,exponentiate = T)
fit<-coxph(Surv(followup, activetb) ~ tst_stratify, data = d2)
tbl_regression(fit,exponentiate = T)

```

#IRR

```{r IRR}
fit<-glm(activetb ~ mantoux_bin+offset(log(followup)),family = poisson(link = "log"), data = d2)
tbl_regression(fit,exponentiate = T)

fit<-glm(activetb ~ igrapos+offset(log(followup)),family = poisson(link = "log"), data = d2)
tbl_regression(fit,exponentiate = T)

fit<-glm(activetb ~ tst10+offset(log(followup)),family = poisson(link = "log"), data = d2)
tbl_regression(fit,exponentiate = T)
fit<-glm(activetb ~ tst15+offset(log(followup)),family = poisson(link = "log"), data = d2)
tbl_regression(fit,exponentiate = T)
fit<-glm(activetb ~ tst_stratify+offset(log(followup)),family = poisson(link = "log"), data = d2)
tbl_regression(fit,exponentiate = T)

```


# quantitative value

The prediction curve using quantitative QFT values shows an odd shape. 

```{r quantitative}
library(rms)
fit_tst<-coxph(Surv(followup, activetb) ~ rcs(mantoux_result,3), data = d2)
d2$pred_tst[!is.na(d2$mantoux_result)] <- predict(fit_tst, data = d2, type="risk")
fit_qft<-coxph(Surv(followup, activetb) ~ rcs(qfngit_tbag_nil,3), data = d2)
d2$pred_qft[!is.na(d2$qfngit_tbag_nil)] <- predict(fit_qft, data = d2, type="risk")
ggplot(d2) +
  geom_smooth(aes(x=qfngit_tbag_nil, y=pred_qft)) 
ggplot(d2) +
  geom_smooth(aes(x=mantoux_result, y=pred_tst)) 

```

Curves using normalized values using PERISKOPE percentile.

```{r normalized}
qft_cat<-c(0,0.001,0.01,0.02,0.03,0.04,0.05,0.06,0.07,0.08,0.09,0.1,0.12,0.13,0.15,0.17,0.2,0.22,0.26,0.3,0.35,0.4,0.45,0.52,0.6,0.69,0.81,0.92,1.07,1.27,1.52,1.77,2.06,2.48,2.94,3.55,4.28,5.1,6.29,7.59,9.18,10,+Inf)
qft_label<-c(1,39,40,49,54,57,60,62,63,65,66,67,69:98)
tst_cat<-c(0,2:23,25,27,31,+Inf)
tst_label<-c(1,52,53,55,57,60,62,64,66,68,72,74,77,79,81,84,86,88,89,91,94:98,99)

d2<-mutate(d2,normqft=cut(qfngit_tbag_nil,breaks=qft_cat,labels=qft_label,right=F))
d2<-mutate(d2,normtst=cut(mantoux_result,breaks=tst_cat,labels=tst_label,right=F))
d2$normtst<-as.numeric(as.character(d2$normtst))
d2$normqft<-as.numeric(as.character(d2$normqft))

library(tidyr)

fit_tst<-coxph(Surv(followup, activetb) ~ rcs(normtst,c(10,50,90)), data = d2)
d2$pred_tst[!is.na(d2$mantoux_result)] <- predict(fit_tst, data = d2, type="risk")
fit_qft<-coxph(Surv(followup, activetb) ~ rcs(normqft,c(10,50,90)), data = d2)
d2$pred_qft[!is.na(d2$normqft)] <- predict(fit_qft, data = d2, type="risk")
d3<-select(d2,pred_tst,pred_qft,normtst,normqft)
d3<-gather(d3, test, norm_value, normtst:normqft)
d3<-mutate(d3,test=ifelse(test=="normtst","TST","IGRA"))
d3<-mutate(d3,pred=ifelse(test=="TST",pred_tst,pred_qft))
d3<-select(d3,norm_value,test,pred)
library(ggplot2)
ggplot(d3) +
  geom_smooth(aes(x=norm_value, y=pred,color=test)) 

```

# Stratified by contact

```{r subgroup}
fit<-glm(activetb ~ mantoux_bin*contact+offset(log(followup)),family = poisson(link = "log"), data = d2)
tbl_regression(fit,exponentiate = T)

fit<-glm(activetb ~ igrapos*contact+offset(log(followup)),family = poisson(link = "log"), data = d2)
tbl_regression(fit,exponentiate = T)
```

# predictors

```{r predictors}
library(dplyr)
d4<-select(d2,activetb,tst15,igrapos,contact,age,sex,prevtbdiag,prevbcg,bmi,followup)
d4<-d4[complete.cases(d4),]
full<- glm(activetb~tst15+igrapos+contact+age+sex+prevtbdiag+prevbcg+bmi+offset(log(followup)), d4,family = poisson(link="log"))
library(MASS)
step.model <- stepAIC(full, direction = "both", 
                      trace = FALSE)
summary(step.model)
```
